refactor: script run

diff --git a/scripts/run b/scripts/run
--- a/scripts/run
+++ b/scripts/run
@@ -4,8 +4,8 @@ SITE_ROOT=$(realpath $(dirname $(realpath $0))/..)
 export HOME=$SITE_ROOT
 # ROOT_DIR=$SITE_ROOT
 
-if [ -e "$SITE_ROOT/cmd_server" ]; then bash $SITE_ROOT/cmd_server _env; fi
-if [ -f "$SITE_ROOT/.env_raw" ]; then source $SITE_ROOT/.env_raw; fi
+# if [ -e "$SITE_ROOT/cmd_server" ]; then bash $SITE_ROOT/cmd_server _env; fi
+# if [ -f "$SITE_ROOT/.env_raw" ]; then source $SITE_ROOT/.env_raw; fi
 source $SITE_ROOT/scripts/base.sh
 
 cd $SITE_ROOT
@@ -17,122 +17,81 @@ ASDF=/massbit/massbitroute/app/gbc/bin/.asdf
 GDNSD_VERSION=v3.8.0
 GDNSD_DIR=$ASDF/installs/gdnsd/$GDNSD_VERSION
 #  $service_dir/gwman/data|http://$GIT_GWMANDEPLOY_WRITE@$GIT_PRIVATE_DOMAIN/massbitroute/gwmandeploy.git|$GWMAN_BRANCH \
+
 _repo() {
-	if [ -e "$SITE_ROOT/cmd_server" ]; then bash $SITE_ROOT/cmd_server _env; fi
-	if [ -f "$SITE_ROOT/.env_raw" ]; then source $SITE_ROOT/.env_raw; fi
-
-	export MBR_ENV=${MBR_ENV:-dev}
-	# export MBRAPP_BRANCH=${MBRAPP_BRANCH:-staging}
-	export ASDF_BRANCH=${ASDF_BRANCH:-$MBR_ENV}
-	export GBC_BRANCH=${GBC_BRANCH:-$MBR_ENV}
-	export SSL_BRANCH=${SSL_BRANCH:-$MBR_ENV}
-	export GWMAN_BRANCH=${GWMAN_BRANCH:-$MBR_ENV}
-	# export NODE_BRANCH=${NODE_BRANCH:-$MBR_ENV}
-	# export GATEWAY_BRANCH=${GATEWAY_BRANCH:-$MBR_ENV}
-	# export STAT_BRANCH=${STAT_BRANCH:-$MBR_ENV}
-	# export MONITOR_BRANCH=${MONITOR_BRANCH:-$MBR_ENV}
-	# export API_BRANCH=${API_BRANCH:-$MBR_ENV}
-	# export SESSION_BRANCH=${SESSION_BRANCH:-$MBR_ENV}
-	# export GIT_BRANCH=${GIT_BRANCH:-$MBR_ENV}
-	export MKAGENT_BRANCH=${MKAGENT_BRANCH:-$MBR_ENV}
-
-	REPOS="\
-$SITE_ROOT/env|$GIT_PRIVATE_READ_URL/massbitroute/env.git|$MBR_ENV \
-/etc/letsencrypt|$GIT_PRIVATE_READ_URL/massbitroute/ssl.git|$SSL_BRANCH \
- $mbr_root/gbc|https://github.com/massbitprotocol/massbitroute_gbc|$GBC_BRANCH \
- $mbr_root/gbc/bin/.asdf|https://github.com/massbitprotocol/massbitroute_asdf|$ASDF_BRANCH \
-  $service_dir/gwman/data|$GIT_PRIVATE_READ_URL/massbitroute/gwmandeploy.git|$GWMAN_BRANCH \
-  $service_dir/gwman|$GIT_PUBLIC_URL/massbitprotocol/massbitroute_gwman.git|$GWMAN_BRANCH \
-$service_dir/mkagent|$GIT_PUBLIC_URL/massbitprotocol/massbitroute_mkagent.git|$MKAGENT_BRANCH \
-"
-}
-_repo
-
-_tune_extra() {
-	if [ ! -f "/etc/logrotate.d/massbit" ]; then
-		cat >/etc/logrotate.d/massbit <<EOF
-$SITE_ROOT/logs/access/*.log
-$SITE_ROOT/logs/nginx/*.log
-$SITE_ROOT/logs/*.log {
-       daily
-       rotate 1
-       delaycompress
-       compress
-       notifempty
-       missingok
-       sharedscripts
-        postrotate
-                [ -f $SITE_ROOT/tmp/nginx.pid ] && kill -USR1 \$(cat $SITE_ROOT/tmp/nginx.pid)
-        endscript
-}
-EOF
-	fi
-}
-_tune_os() {
-	#dns
-	sed 's/#DNSStubListener=yes/DNSStubListener=no/' /etc/systemd/resolved.conf -i
-	pkill -f systemd-resolve
-
-	rm /etc/resolv.conf
-	echo nameserver 8.8.8.8 >/etc/resolv.conf
-	systemctl stop systemd-resolved
-	systemctl disable systemd-resolved
-}
-
-_init() {
-	if [ -z "$GIT_PRIVATE_READ_URL" ]; then
-		echo "Need GIT_PRIVATE_READ_URL"
+	if [ -z "$MBR_ENV" ]; then
+		echo "MBR_ENV missing"
 		exit 1
 	fi
-	cat <<EOF >$SITE_ROOT/.env
-export GIT_PUBLIC_URL="https://github.com"
-export MBR_ENV=$MBR_ENV
-EOF
 
-	# _tune_os
-	# if [ ! -f "$SITE_ROOT/.env" ]; then
-	# 	echo "$MBR_ENV" >$SITE_ROOT/.env
-	# fi
-
-	source $SITE_ROOT/.env
-
-	_repo
-
-	_git_clone $GIT_PRIVATE_READ_URL/massbitroute/env.git $SITE_ROOT/env $MBR_ENV
-	_git_clone $GIT_PUBLIC_URL/massbitprotocol/massbitroute_gbc.git /massbit/massbitroute/app/gbc
-
-	# bash $SITE_ROOT/cmd_server _env
-	# source $SITE_ROOT/.env_raw
-	_repo
+	REPOS=""
 }
+
+_repo_private() {
+
+	if [ -z "$MBR_ENV" ]; then
+		echo "MBR_ENV missing"
+		exit 1
+	fi
+	if [ -z "$GIT_PRIVATE_READ_URL" ]; then
+		echo "GIT_PRIVATE_READ_URL missing"
+		exit 1
+	fi
+
+	export SSL_BRANCH=${SSL_BRANCH:-$MBR_ENV}
+	export MKAGENT_BRANCH=${MKAGENT_BRANCH:-$MBR_ENV}
+
+	export GWMAN_BRANCH=${GWMAN_BRANCH:-$MBR_ENV}
+	export GWMANDEPLOY_BRANCH=${GWMANDEPLOY_BRANCH:-$MBR_ENV}
+
+	_env
+
+	REPOS_RUNTIME="\
+  $service_dir/gwman/data|$GIT_PRIVATE_READ_URL/massbitroute/gwmandeploy.git|$GWMANDEPLOY_BRANCH \
+"
+
+	REPOS_PRIVATE="\
+$SITE_ROOT/env|$GIT_PRIVATE_READ_URL/massbitroute/env.git|$ENV_BRANCH \
+"
+}
+# _repo
+
+# _tune_extra() {
+# 	if [ ! -f "/etc/logrotate.d/massbit" ]; then
+# 		cat >/etc/logrotate.d/massbit <<EOF
+# $SITE_ROOT/logs/access/*.log
+# $SITE_ROOT/logs/nginx/*.log
+# $SITE_ROOT/logs/*.log {
+#        daily
+#        rotate 1
+#        delaycompress
+#        compress
+#        notifempty
+#        missingok
+#        sharedscripts
+#         postrotate
+#                 [ -f $SITE_ROOT/tmp/nginx.pid ] && kill -USR1 \$(cat $SITE_ROOT/tmp/nginx.pid)
+#         endscript
+# }
+# EOF
+# 	fi
+# }
+# _tune_os() {
+# 	#dns
+# 	sed 's/#DNSStubListener=yes/DNSStubListener=no/' /etc/systemd/resolved.conf -i
+# 	pkill -f systemd-resolve
+
+# 	rm /etc/resolv.conf
+# 	echo nameserver 8.8.8.8 >/etc/resolv.conf
+# 	systemctl stop systemd-resolved
+# 	systemctl disable systemd-resolved
+# }
+
 _prepare() {
 	echo "Prepare"
 	mkdir -p $SITE_ROOT/logs/nginx $SITE_ROOT/db $SITE_ROOT/tmp $SITE_ROOT/db $SITE_ROOT/zones $SITE_ROOT/run $SITE_ROOT/data
 
-	# 	cd $SITE_ROOT
-	# 	for _d in monitors.d failover.d weighted.d multivalue.d datacenter.d geolocation.d/maps.d geolocation.d/resources.d; do
-	# 		_dir=data/conf.d/$_d
-	# 		mkdir -p $_dir
-	# 		touch $_dir/_default
-	# 	done
-
-	# 	if [ ! -f "$SITE_ROOT/data/conf.d/monitors.d/gateway" ]; then
-	# 		cat >$SITE_ROOT/data/conf.d/monitors.d/gateway <<EOF
-	#  gateway_check => {
-	#     plugin => tcp_connect,
-	#     port => 443,
-	#     up_thresh => 20,
-	#     ok_thresh => 10,
-	#     down_thresh => 10,
-	#     interval => 10,
-	#     timeout => 3,
-	#   }
-	# EOF
-	# fi
-
 	if [ ! -f "$SITE_ROOT/geoip/GeoIP2-City.mmdb" ]; then
-		# apt update
-		# apt-get install -y xz-utils
 		tar -xvJf $SITE_ROOT/geoip/GeoIP2-City.mmdb.tar.xz -C $SITE_ROOT/geoip
 	fi
 
@@ -193,16 +152,43 @@ EOF
 }
 
 _install_repos() {
-	_git_config
-
-	for _pathgit in $REPOS; do
-		_repo
-		_path=$(echo $_pathgit | cut -d'|' -f1)
-		_url=$(echo $_pathgit | cut -d'|' -f2)
-		_branch=$(echo $_pathgit | cut -d'|' -f3)
-		_git_clone $_url $_path $_branch
-	done
+	if [ -z "$MBR_ENV" ]; then
+		echo "MBR_ENV missing"
+		exit 1
+	fi
+	_repo
+	_install_sources $REPOS
+	_install_status=$?
+	return $_install_status
 }
+
+_update_repos() {
+	if [ -z "$MBR_ENV" ]; then
+		echo "MBR_ENV missing"
+		exit 1
+	fi
+	if [ -z "$GIT_PRIVATE_READ_URL" ]; then
+		echo "Need GIT_PRIVATE_READ_URL"
+		exit 1
+	fi
+	_repo_private
+	_update_sources $REPOS_PRIVATE
+	_update_status=$?
+	_update_sources $REPOS_RUNTIME
+	return $_update_status
+}
+
+# _install_repos() {
+# 	_git_config
+
+# 	for _pathgit in $REPOS; do
+# 		_repo
+# 		_path=$(echo $_pathgit | cut -d'|' -f1)
+# 		_url=$(echo $_pathgit | cut -d'|' -f2)
+# 		_branch=$(echo $_pathgit | cut -d'|' -f3)
+# 		_git_clone $_url $_path $_branch
+# 	done
+# }
 _supervisor() {
 	ln -sf /massbit/massbitroute/app/gbc /massbit/massbitroute/app/src/gbc
 	ln -sf /massbit/massbitroute/app/gbc/bin/openresty /usr/local/openresty
@@ -222,7 +208,7 @@ _supervisor() {
 	fi
 }
 _install_one() {
-	_init
+	# _init
 	_prepare
 	_install_repos
 }
@@ -232,12 +218,12 @@ _install() {
 	_supervisor
 }
 
-_add_cron() {
-	cat <<EOF >/tmp/crontab
-0 0 * * * $SITE_ROOT/scripts/run _update_ssl
-EOF
-	crontab /tmp/crontab
-}
+# _add_cron() {
+# 	cat <<EOF >/tmp/crontab
+# 0 0 * * * $SITE_ROOT/scripts/run _update_ssl
+# EOF
+# 	crontab /tmp/crontab
+# }
 
 _rebuild_conf() {
 	_dir=$SITE_ROOT/data/zones
@@ -281,45 +267,40 @@ _reload_gdnsd() {
 	fi
 }
 _reload() {
-	_add_cron
+	# _add_cron
 	_rebuild_conf
 	_reload_gdnsd
 	$SITE_ROOT/cmd_server _update
 }
 
-_update_ssl() {
-	_git_config
-	git_ssl='git -C /etc/letsencrypt'
-	bash $SITE_ROOT/cert.sh _renew
-	$git_ssl add /etc/letsencrypt
-	$git_ssl commit -m update
-	$git_ssl push origin master
-}
+# _update_ssl() {
+# 	_git_config
+# 	git_ssl='git -C /etc/letsencrypt'
+# 	bash $SITE_ROOT/cert.sh _renew
+# 	$git_ssl add /etc/letsencrypt
+# 	$git_ssl commit -m update
+# 	$git_ssl push origin master
+# }
 
-_update_repos() {
-	_repo
-	_update_sources $REPOS
-	_st_repo=$?
-	return $_st_repo
-}
+# _update_repos() {
+# 	_repo
+# 	_update_sources $REPOS
+# 	_st_repo=$?
+# 	return $_st_repo
+# }
 
 _update() {
-	if [ ! -f "$SITE_ROOT/.env" ]; then
-		cat <<EOF >$SITE_ROOT/.env
-export GIT_PUBLIC_URL="https://github.com"
-export MBR_ENV=$MBR_ENV
-EOF
-	fi
-	_st_update=0
 	echo "Update"
-	# _update_repos
-	# _st_update=$?
+	_prepare
+	_st_update=0
+
+	_update_repos
+	_st_update=$?
+	_commit_repos
 	return $_st_update
 }
-_monitor() {
-	echo mbr-gwman >vars/TYPE
 
-	_tune_extra
+_monitor() {
 	_update
 	is_reload=$?
 
@@ -335,9 +316,9 @@ _service_gdnsd() {
 
 _run() {
 	rm -rf $SITE_ROOT/tmp/*
-	sleep 3
 	mkdir -p $SITE_ROOT/run
 	touch $SITE_ROOT/run/admin_state
+	_update
 	$SITE_ROOT/start_server
 }
 
